### ISSUE TITLE
Todo list [24.06.25]

### ISSUE THREAD

**Issue by lucy0701** [lucy0701/Simpang_Server#19]
- [x] Schema : timestamps 활용
- [x] 재사용 가능 함수 검토 분리
- [x] 상수 정의
- [x] import/order 설정

* 전체적인 리팩토링

- [x] mongoDB 연결 
- [x] Swagger 설정

**Comment by agmon5959** [comment]
👍

**Comment by lucy0701** [comment]
24.06.26 완료
