### ISSUE TITLE
[24.08.02] todo list

### ISSUE THREAD

**Issue by lucy0701** [lucy0701/Simpang_Server#46]
- [ ] mbti 테이블 분리
  - [x] 결과 계산 개선 : 앞단에서 문자열 전송 

- [x] Result 내용 전체 -> ID만 반환 되도록 수정

- [ ] 신규 심리테스트 타입 추가 ( Mbti 말고 간단한 테스트 )
- [ ] 컨텐츠 검색
- [ ] my page: 좋아요 목록
