### ISSUE TITLE
Todo List [24.06.21 - 24.06.30]

### ISSUE THREAD

**Issue by lucy0701** [lucy0701/Simpang_Server#8]
### Content
- [x] Schema: creator 추가 
- [x] 오름차순 / 내림차순 정렬 추가

### Result 
- [x] User - Result History : 최대  50개 (신규 생성시 제일 오래된 데이터 삭제)

### JWT
- [x] 토큰 : sub, role
- [x] 모든 req api에서 토큰 확인 : userInfo 있을 경우 저장, 없을 경우 undefinde 
- [x] 로그인 / 권한이 필요할 경우 검증 미들웨어 사용
- [x] 유저 권한
  - [x] User: 일반 유저 
  - [x] Creator: 자신이 업로드한 콘텐츠 확인 / 수정 / 삭제 가능
  - [x] Admin : 모든 콘텐츠 수정 / 삭제 가능
